#!/usr/bin/env ansible-playbook

#
# Usage:
#    chmod 0700 main.yml
#    ./main.yml -i inventory/prod --limit <something from inventory> --user=if_you_need_it
#

- hosts: linux
  become: True
  gather_facts: False

  tasks:
    - name: Remove suid-bit from pkexec
      file:
        path: /usr/bin/pkexec
        owner: root
        group: root
        mode: 0755
